<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <link rel="stylesheet" type="text/css" href="/css/admin.css" />
        <script type="text/javascript" src="/ckeditor/ckeditor.js"></script>
        <script type="text/javascript" src="/ckfinder/ckfinder.js"></script>
        <script type="text/javascript" src="/js/admin.js"></script>
    </head>

    <body class="yui-skin-sam">

        <div id="top"><!-- Start top area -->

            <div class="title">Edit<?php echo ($this->titleSuffix) ? ' ' . $this->escapeHtml(strtolower($this->titleSuffix)) : '' ?>:
            <?php echo $this->escapeHtml($this->typeName) ?> - <i><?php echo $this->escapeHtml($this->blockName) ?></i></div>
            <?php echo $this->messages() ?>
            <div class="info"><img src="/images/required_star.png" alt="Required"> indicates required field</div>

        </div><!-- End top area -->

        <?php
        $form = $this->form;
        $form->setAttribute('name', 'main')->prepare();
        ?>

        <?php echo $this->form()->openTag($form) ?>

            <?php echo $this->adminFormElement($form->get('id')) ?>
            <?php echo $this->adminFormElement($form->get('partial')) ?>
            <?php echo $this->adminFormElement($form->get('token')) ?>

            <div id="stage"><!-- Start stage area -->

                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Notes</div>
                        <p>
                            <?php if (empty($this->blockNotes)) : ?>
                            No notes found
                            <?php else : ?>
                            <?php foreach ($this->blockNotes as $note) : ?>
                            <?php echo $this->date($note->time, 'F j Y H:i') . ' - ' .
                            $this->escapeHtml($note->username) . ' - ' .
                            $this->escapeHtml($note->text) ?><br />
                            <?php endforeach; ?>
                            <?php endif; ?>
                        </p>
                    </div>
                </div><!-- End fieldset -->

                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Content</div>

                        <?php if ($form->has('fields')) : ?>
                        <?php foreach ($form->get('fields')->getElements() as $element) : ?>
                        <?php echo $this->adminFormElement($element) ?>
                        <?php endforeach; ?>
                        <?php endif; ?>

                    </div>

                </div><!-- End fieldset -->
            </div><!-- End stage area -->

                <div class="submit-area">

                    <?php echo $this->adminFormElement($form->get('note')) ?>

                    <div class="form-element">
                        <div class="form-inputs line-up">
                            <?php
                            $form->get('save')->setAttribute('class', 'button');
                            echo $this->formElement($form->get('save'));
                            ?>
                        </div>
                    </div>

                    <div class="form-element">
                        <div class="form-inputs line-up">
                            <?php
                            $form->get('publish')->setAttribute('class', 'button');
                            echo $this->formElement($form->get('publish'));
                            ?>
                        </div>
                    </div>

                </div>

        <?php echo $this->form()->closeTag() ?>

    </body>
</html>
