<?php
$this->headScript()->appendFile('/ckeditor/ckeditor.js');
$this->headScript()->appendFile('/ckfinder/ckfinder.js');
?>

        <div class="row">
            <div class="col-md-12">

                <h1>Edit<?php echo ($this->titleSuffix) ? ' ' . $this->escapeHtml(strtolower($this->titleSuffix)) : '' ?>
                <?php echo $this->escapeHtml($this->typeName) ?> <small><?php echo $this->escapeHtml($this->blockName) ?></small></h1>

                <?php
                $form = $this->form;
                $form->setAttribute('name', 'main');
                $form->setAttribute('class', 'form-horizontal');
                $form->prepare();
                ?>

                <?php echo $this->form()->openTag($form) ?>

                    <?php echo $this->adminFormElement($form->get('id')) ?>
                    <?php echo $this->adminFormElement($form->get('partial')) ?>
                    <?php echo $this->adminFormElement($form->get('token')) ?>

                    <fieldset>
                        <legend>Notes</legend>
                        <p>
                            <?php if (empty($this->blockNotes)) : ?>
                            No notes found
                            <?php else : ?>
                            <?php foreach ($this->blockNotes as $note) : ?>
                            <?php echo $this->date($note->time, 'F j Y H:i') . ' - ' .
                            $this->escapeHtml($note->username) . ' - ' .
                            $this->escapeHtml($note->text) ?><br />
                            <?php endforeach; ?>
                            <?php endif; ?>
                        </p>
                    </fieldset>

                    <fieldset>
                        <legend>Content</legend>

                        <?php if ($form->has('fields')) : ?>
                        <?php foreach ($form->get('fields')->getElements() as $element) : ?>
                        <?php echo $this->adminFormElement($element) ?>
                        <?php endforeach; ?>
                        <?php endif; ?>

                    </fieldset>

                    <?php echo $this->adminFormElement($form->get('note')) ?>

                    <div class="form-group">
                        <div class="col-md-10 col-md-offset-2">

                                <?php
                                $form->get('save')->setAttribute('class', 'btn btn-warning');
                                echo $this->formElement($form->get('save'));
                                ?>

                                <?php
                                $form->get('publish')->setAttribute('class', 'btn btn-success');
                                echo $this->formElement($form->get('publish'));
                                ?>

                        </div>
                    </div>

                <?php echo $this->form()->closeTag() ?>

            </div>
        </div>
