
        <div class="row">
            <div class="col-md-12">

                <h1>Blocks</h1>

                <div class="panel panel-default">

                    <div class="panel-heading clearfix">
                        <?php if ($this->allowCreate) : ?>
                        <a class="btn btn-default pull-left" href="<?php echo $this->url('block', ['action' => 'create']); ?>">Create new</a>
                        <?php endif; ?>
                        <form method="GET" class="form-inline pull-right">
                            <div class="form-group">
                                <label class="sr-only" for="search">Search</label>
                                <div class="input-group">
                                    <input type="text" name="search" required="required" id="search" class="form-control" placeholder="Search">
                                    <span class="input-group-btn">
                                        <button class="btn btn-default" type="submit">
                                            <i class="glyphicon glyphicon-search"></i>
                                        </button>
                                    </span>
                                </div>
                            </div>
                        </form>
                    </div>

                    <table class="table">
                        <tbody>
                            <?php if ($this->blockItems) : ?>
                            <?php echo $this->partialLoop('boxspaced/cms-block-module/block/block-item.phtml', $this->blockItems) ?>
                            <?php else : ?>
                            <tr class="odd"><td width="100%">Empty result set</td><td colspan="5">&nbsp;</td></tr>
                            <?php endif; ?>
                        </tbody>
                    </table>

                </div>

                <?php echo $this->paginationControl(
                    $this->paginator,
                    'Sliding',
                    'boxspaced/cms-core-module/partial/pagination.phtml'
                ); ?>

            </div>
        </div>
