
        <div class="row">
            <div class="col-md-12">

                <h1>Index of: blocks</h1>

                <?php if ($this->allowCreate) : ?>
                <div class="actions">
                    <img src="/images/icons/add.png" alt="Add icon" />
                    <a class="link-button" href="<?php echo $this->url('block', ['action' => 'create']); ?>">Create new</a>
                </div>
                <?php endif; ?>

                <table class="table">
                    <thead>
                        <tr>
                            <th>&nbsp;</th>
                            <th colspan="5">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        <?php if ($this->blockItems) : ?>
                        <?php echo $this->partialLoop('boxspaced/cms-block-module/block/block-item.phtml', $this->blockItems) ?>
                        <?php else : ?>
                        <tr class="odd"><td width="100%">Empty result set</td><td colspan="5">&nbsp;</td></tr>
                        <?php endif; ?>
                    </tbody>
                </table>

                <?php echo $this->paginationControl(
                    $this->paginator,
                    'Sliding',
                    'boxspaced/cms-core-module/partial/pagination.phtml'
                ); ?>

            </div>
        </div>
