<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html lang="en">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
        <title></title>
        <meta name="description" content="" />
        <meta name="keywords" content="" />
        <link rel="stylesheet" type="text/css" href="/css/admin.css" />
        <script type="text/javascript" src="/js/admin.js"></script>

    </head>

    <body class="yui-skin-sam">

        <div id="top"><!-- Start top area -->

            <div class="title">Publish:
                <?php echo $this->escapeHtml($this->typeName) ?> - <i><?php echo $this->escapeHtml($this->blockName) ?></i></div>
            <?php echo $this->messages() ?>
            <div class="info"><img src="/images/required_star.png" alt="Required"> indicates required field</div>

        </div><!-- End top area -->

        <?php
        $form = $this->form;
        $form->setAttribute('name', 'main')->prepare();
        ?>

        <?php echo $this->form()->openTag($form) ?>

            <?php echo $this->adminFormElement($form->get('id')) ?>
            <?php echo $this->adminFormElement($form->get('partial')) ?>
            <?php echo $this->adminFormElement($form->get('token')) ?>

            <div id="stage"><!-- Start stage area -->

                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Notes</div>
                        <p>
                            <?php if (empty($this->blockNotes)) : ?>
                                No notes found
                            <?php else : ?>
                                <?php foreach ($this->blockNotes as $note) : ?>
                                    <?php
                                    echo $this->date($note->time, 'F j Y H:i') . ' - ' .
                                    $this->escapeHtml($note->username) . ' - ' .
                                    $this->escapeHtml($note->text)
                                    ?><br />
                                <?php endforeach; ?>
                            <?php endif; ?>
                        </p>
                    </div>
                </div><!-- End fieldset -->

                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Lifespan</div>

                        <?php echo $this->adminFormElement($form->get('liveFrom')) ?>
                        <div style="position: relative; top: -38px; left: 315px;">
                            <a href="javascript:cal1.popup();"><img src="/images/icons/calendar.png" width="16" height="16" border="0"
                                 title="Pick date/time" alt="Pick date/time"></a> or <a href="javascript:set_field_value('main', 'liveFrom',
                              '<?php echo date('Y-m-d') ?> 00:00:00');">Immediately</a></div>

                        <?php echo $this->adminFormElement($form->get('expiresEnd')) ?>
                        <div style="position: relative; top: -38px; left: 315px;">
                        <a href="javascript:cal2.popup();"><img src="/images/icons/calendar.png" width="16" height="16" border="0"
                             title="Pick date/time" alt="Pick date/time"></a> or <a href="javascript:set_field_value('main', 'expiresEnd',
                           '2038-01-19 00:00:00');">Never</a></div>

                    </div>
                </div><!-- End fieldset -->

                <div class="white-box"><!-- Start fieldset -->
                    <div class="white-box-rounded-corner-top"><div></div></div>
                    <div class="white-box-content">
                        <div class="white-box-title">Settings</div>

                            <?php echo $this->adminFormElement($form->get('name')) ?>

                            <?php
                            $form->get('templateId')->setAttribute('onChange', 'submit_partial(this.form)');
                            if ($this->templateDescription) :
                                $currentDesc = $form->get('templateId')->getOption('description');
                                $form->get('templateId')->setOption('description', $currentDesc . $this->templateDescription);
                            endif;
                            if (count($form->get('templateId')->getValueOptions()) > 1) :
                                echo $this->adminFormElement($form->get('templateId'));
                            else :
                                echo $this->formHidden($form->get('templateId'));
                            endif;
                            ?>
                    </div>
                </div><!-- End fieldset -->

            </div><!-- End stage area -->

            <div class="submit-area">

                <div class="form-element">
                    <div class="form-inputs line-up">
                        <?php
                        $form->get('publish')->setAttribute('class', 'button');
                        echo $this->formElement($form->get('publish'));
                        ?>
                    </div>
                </div>

            </div>

        <?php echo $this->form()->closeTag() ?>

        <script language="JavaScript">
            <!--
            var input1 = document.getElementById('live-from');
            var cal1 = new calendar(input1);
            cal1.year_scroll = true;
            cal1.time_comp = true;

            var input2 = document.getElementById('expires-end');
            var cal2 = new calendar(input2);
            cal2.year_scroll = true;
            cal2.time_comp = true;
            -->
        </script>
    </body>
</html>
