
        <div class="row">
            <div class="col-md-12">

                <h1>
                    Publish
                    <span class="type"><?php echo $this->escapeHtml($this->typeName) ?></span>
                    <small><?php echo $this->escapeHtml($this->blockName) ?></small>
                </h1>

                <?php
                $form = $this->form;
                $form->setAttribute('name', 'main');
                $form->setAttribute('class', 'form-horizontal');
                $form->prepare();
                ?>

                <?php echo $this->form()->openTag($form) ?>

                    <?php echo $this->adminFormElement($form->get('id')) ?>
                    <?php echo $this->adminFormElement($form->get('partial')) ?>
                    <?php echo $this->adminFormElement($form->get('token')) ?>

                    <fieldset>
                        <legend>Notes</legend>

                        <div class="form-group">
                            <label class="col-md-2 control-label">&nbsp;</label>
                            <div class="col-md-10">
                                <p class="form-control-static">
                                    <?php if (empty($this->blockNotes)) : ?>
                                        No notes found
                                    <?php else : ?>
                                        <?php foreach ($this->blockNotes as $note) : ?>
                                            <?php
                                            echo $this->date($note->time, 'F j Y H:i') . ' - ' .
                                            $this->escapeHtml($note->username) . ' - ' .
                                            $this->escapeHtml($note->text)
                                            ?><br />
                                        <?php endforeach; ?>
                                    <?php endif; ?>
                                </p>
                            </div>
                        </div>

                    </fieldset>

                    <fieldset>
                        <legend>Lifespan</legend>

                        <?php
                        $form->get('liveFrom')->setAttribute('class', 'live-from-datepicker');
                        echo $this->adminFormElement($form->get('liveFrom'));
                        ?>

                        <?php
                        $form->get('expiresEnd')->setAttribute('class', 'expires-end-datepicker');
                        echo $this->adminFormElement($form->get('expiresEnd'));
                        ?>

                    </fieldset>

                    <fieldset>
                        <legend>Settings</legend>

                        <?php echo $this->adminFormElement($form->get('name')) ?>

                        <?php
                        $form->get('templateId')->setAttribute('onChange', 'submit_partial(this.form)');
                        if ($this->templateDescription) :
                            $currentDesc = $form->get('templateId')->getOption('description');
                            $form->get('templateId')->setOption('description', $currentDesc . $this->templateDescription);
                        endif;
                        if (count($form->get('templateId')->getValueOptions()) > 1) :
                            echo $this->adminFormElement($form->get('templateId'));
                        else :
                            echo $this->formHidden($form->get('templateId'));
                        endif;
                        ?>
                    </fieldset>

                    <fieldset>
                        <legend>Submit</legend>

                        <div class="form-group">
                            <div class="col-md-10 col-md-offset-2">

                                <?php
                                $form->get('publish')->setAttribute('class', 'btn btn-success');
                                echo $this->formElement($form->get('publish'));
                                ?>

                            </div>
                        </div>

                    </fieldset>

                <?php echo $this->form()->closeTag() ?>

            </div>
        </div>
